apiVersion: "v1"
kind: Pod
metadata:
  name: shelf-db
  labels:
    name: shelf-db
    app: shelf
spec:
  containers:
    - name: shelf-db
      image: shelf-postgre:1.0
      ports:
        - containerPort: 5432 
          protocol: TCP
    
