apiVersion: "v1"
kind: Pod
metadata:
  name: shelf-db
  labels:
    app: shelf-db
spec:
  containers:
    - name: shelf-db
      image: daleksandrov/shelf-db:1.0
      ports:
        - containerPort: 5432 
          protocol: TCP

---    
apiVersion: v1
kind: Service
metadata:
  name: shelf-db
spec:
  ports:
  - protocol: TCP
    port: 5432
    name: shelf-db
    targetPort: 5432
  selector:
    app: shelf-db
